## 🚀 Advanced MLflow: Deep Learning with Hyperparameter Optimization

### What You'll Learn:
This is the **most advanced notebook** in the project! We'll use:
- **Keras/TensorFlow**: Build a deep learning neural network
- **Hyperopt**: Intelligently search for best hyperparameters (smarter than grid search!)
- **MLflow**: Track every experiment and compare results
- **Wine Quality Prediction**: Predict wine quality from chemical properties

### Key Features:
1. **Neural Networks instead of classical ML**: Use deep learning for complex patterns
2. **Hyperopt (not GridSearchCV)**: Uses Bayesian optimization - tests fewer combinations but smarter!
3. **Nested Runs**: Each hyperopt iteration creates a sub-run tracked in MLflow
4. **Model Deployment**: Load and use the best model for predictions

### Real-World Significance:
This workflow is exactly what companies use to:
- Train neural networks efficiently
- Track thousands of experiments automatically
- Deploy models to production
- A/B test different model versions

In [ ]:
# ============================================================================
# STEP 1: Import All Required Libraries
# ============================================================================

# Deep Learning
import keras                                    # Neural network library
import tensorflow as tf                        # TensorFlow backend
print(f"✅ Keras version: {keras.__version__}")

# Scientific Computing
import numpy as np                              # Numerical operations
import pandas as pd                             # Data manipulation

# Hyperparameter Optimization
from hyperopt import STATUS_OK, Trials, fmin, hp, tpe  
# - STATUS_OK: Status code for successful run
# - Trials: Stores all hyperopt trials/runs
# - fmin: Function minimization (find best hyperparams)
# - hp: Hyperparameter space definition
# - tpe: Tree-structured Parzen Estimator (smart search algorithm)

# Model Evaluation
from sklearn.metrics import mean_squared_error  # Calculate model error
from sklearn.model_selection import train_test_split  # Split data

# MLflow Tracking
import mlflow                                  # Experiment tracking
from mlflow.models import infer_signature     # Create model signature

print("✅ All libraries imported successfully!")

d:\anaconda\envs\mlflow_env\lib\site-packages\hyperopt\atpe.py:19: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [ ]:
# ============================================================================
# STEP 2: Load Wine Quality Dataset from MLflow Repository
# ============================================================================
# This dataset contains physicochemical properties of Portuguese white wines
# Features: Fixed acidity, volatile acidity, citric acid, alcohol, sulfates, etc.
# Target: Quality score (3-9, higher = better quality)

print("📥 Loading Wine Quality dataset from MLflow repository...\n")

# Load from URL (MLflow's official test dataset)
data = pd.read_csv(
    "https://raw.githubusercontent.com/mlflow/mlflow/master/tests/datasets/winequality-white.csv",
    sep=";"  # US Portuguese CSV uses semicolon as separator
)

print(f"✅ Dataset loaded!")
print(f"   Shape: {data.shape[0]} samples × {data.shape[1]} features")
print(f"\n📊 First few rows:")
print(data.head())

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [ ]:
# ============================================================================
# STEP 3: Split Data into Training and Test Sets
# ============================================================================
# We'll use:
# - 75% for training + validation (model gets to learn)
# - 25% for testing (evaluate on completely unseen data)

print("🔀 Splitting data...\n")

train, test = train_test_split(data, test_size=0.25, random_state=42)
print(f"✅ Data split:")
print(f"   Training + Validation: {len(train)} samples (75%)")
print(f"   Testing: {len(test)} samples (25%)")
print(f"\n📊 Training set sample:")
print(train.head())

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
2835,6.3,0.25,0.22,3.30,0.048,41.0,161.0,0.99256,3.16,0.50,10.5,6
1157,7.8,0.30,0.29,16.85,0.054,23.0,135.0,0.99980,3.16,0.38,9.0,6
744,7.4,0.38,0.27,7.50,0.041,24.0,160.0,0.99535,3.17,0.43,10.0,5
1448,7.4,0.16,0.49,1.20,0.055,18.0,150.0,0.99170,3.23,0.47,11.2,6
3338,7.2,0.27,0.28,15.20,0.046,6.0,41.0,0.99665,3.17,0.39,10.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4426,6.2,0.21,0.52,6.50,0.047,28.0,123.0,0.99418,3.22,0.49,9.9,6
466,7.0,0.14,0.32,9.00,0.039,54.0,141.0,0.99560,3.22,0.43,9.4,6
3092,7.6,0.27,0.52,3.20,0.043,28.0,152.0,0.99129,3.02,0.53,11.4,6
3772,6.3,0.24,0.29,13.70,0.035,53.0,134.0,0.99567,3.17,0.38,10.6,6
860,8.1,0.27,0.35,1.70,0.030,38.0,103.0,0.99255,3.22,0.63,10.4,8

In [15]:
train[["quality"]].values.ravel()

array([6, 6, 5, ..., 6, 6, 8], shape=(3673,))

In [ ]:
# ============================================================================
# STEP 4: Further Split Data and Separate Features from Target
# ============================================================================
# We need 3 datasets:
# 1. Train: Teach the model (60% of original)
# 2. Validation: Tune hyperparameters and prevent overfitting (15% of original)
# 3. Test: Final evaluation on completely unseen data (25% of original)

print("🔀 Creating train/validation/test sets...\n")

# ============================================================================
# Prepare Training Data
# ============================================================================
# x = features (all columns except quality)
# y = target (quality score, what we want to predict)
train_x = train.drop(["quality"], axis=1).values  # Convert to NumPy array
train_y = train[["quality"]].values.ravel()       # Target values (flattened to 1D)

print(f"✅ Training set: {train_x.shape[0]} samples × {train_x.shape[1]} features")

# ============================================================================
# Prepare Test Data
# ============================================================================
test_x = test.drop(["quality"], axis=1).values
test_y = test[["quality"]].values.ravel()

print(f"✅ Test set: {test_x.shape[0]} samples × {test_x.shape[1]} features")

# ============================================================================
# Split training data into train and validation
# ============================================================================
# 80% for actual training, 20% for validation during training
train_x, valid_x, train_y, valid_y = train_test_split(
    train_x, train_y, test_size=0.20, random_state=42
)

print(f"✅ Final split:")
print(f"   Train: {len(train_x)} samples")
print(f"   Validation: {len(valid_x)} samples")
print(f"   Test: {len(test_x)} samples")

# Create model signature for MLflow
signature = infer_signature(train_x, train_y)
print(f"\n✅ Model signature created")

In [17]:
np.mean(train_x,axis=0)

array([6.86621852e+00, 2.80377808e-01, 3.32597005e-01, 6.42164738e+00,
       4.55513955e-02, 3.53556841e+01, 1.38792376e+02, 9.94074221e-01,
       3.18919333e+00, 4.88396869e-01, 1.05005673e+01])

In [18]:
print(np.mean(train_x,axis=1))

[15.79594545 14.50073182 16.48442727 ... 12.97630182 17.94385455
 22.38198182]

In [ ]:
# ============================================================================
# STEP 5: Define Neural Network Training Function
# ============================================================================
# This function:
# 1. Creates a neural network with specific hyperparameters
# 2. Trains it on the training data
# 3. Evaluates it on validation data
# 4. Logs everything to MLflow
# 5. Returns the result for hyperopt to optimize

def train_model(params, epochs, train_x, train_y, valid_x, valid_y, test_x, test_y):
    """
    Build, train, and evaluate a neural network with given hyperparameters.
    
    Parameters:
    -----------
    params: dict with 'lr' (learning rate) and 'momentum' (optimizer momentum)
    epochs: number of training iterations
    train_x/y: training data
    valid_x/y: validation data (for early stopping, monitoring)
    test_x/y: test data (final evaluation)
    
    Returns:
    --------
    Dictionary with 'loss' (RMSE), 'status', and 'model'
    """
    
    # ====================================================================
    # 1. Calculate Normalization Parameters
    # ====================================================================
    # Neural networks perform better with normalized data (mean=0, std=1)
    mean = np.mean(train_x, axis=0)  # Mean of each feature
    var = np.var(train_x, axis=0)    # Variance of each feature
    
    # ====================================================================
    # 2. Define Neural Network Architecture
    # ====================================================================
    # Sequential: Stack layers one after another
    # This creates: Input → Normalize → Dense(64) → Dense(1) → Output
    
    model = keras.Sequential([
        keras.Input(shape=[train_x.shape[1]]),  # Input dim = number of wine features
        
        # Normalization layer: Scales input data to have mean=0, variance=1
        keras.layers.Normalization(mean=mean, variance=var),
        
        # Hidden layer: 64 neurons with ReLU activation
        # - 64 neurons allow the model to learn complex patterns
        # - ReLU (Rectified Linear Unit) = max(0, x) - very common activation
        keras.layers.Dense(64, activation="relu"),
        
        # Output layer: 1 neuron (predict 1 value: wine quality)
        # - No activation = linear regression head
        keras.layers.Dense(1)
    ])
    
    # ====================================================================
    # 3. Compile the Model
    # ====================================================================
    # Tell Keras how to train the model
    model.compile(
        # SGD optimizer with hyperparameters from hyperopt
        optimizer=keras.optimizers.SGD(
            learning_rate=params["lr"],      # How much to update weights each step
            momentum=params["momentum"]       # Momentum helps optimization
        ),
        loss="mean_squared_error",           # Loss function (for regression)
        metrics=[keras.metrics.RootMeanSquaredError()]  # Metric to monitor
    )
    
    # ====================================================================
    # 4. Train with MLflow Tracking
    # ====================================================================
    # nested=True: This is a sub-run under a parent run
    with mlflow.start_run(nested=True):
        print(f"   Training with lr={params['lr']:.2e}, momentum={params['momentum']:.2f}")
        
        # Train the model
        # - validation_data: Used to monitor overfitting (not for training)
        # - epochs: How many times to go through the data
        # - batch_size: How many samples per update step
        model.fit(
            train_x, train_y,
            validation_data=(valid_x, valid_y),
            epochs=epochs,
            batch_size=64,
            verbose=0  # No verbose output (training happens in background)
        )
        
        # ====================================================================
        # 5. Evaluate on Validation Data
        # ====================================================================
        # This is what hyperopt will try to minimize
        eval_result = model.evaluate(valid_x, valid_y, batch_size=64, verbose=0)
        eval_rmse = eval_result[1]  # Extract RMSE metric (lower is better)
        
        # ====================================================================
        # 6. Log to MLflow
        # ====================================================================
        # Save hyperparameters and metrics so we can track this run
        mlflow.log_params(params)
        mlflow.log_metric("validation_rmse", eval_rmse)
        
        # Save the model
        mlflow.tensorflow.log_model(model, "model", signature=signature)
        
        # ====================================================================
        # 7. Return Result for Hyperopt
        # ====================================================================
        # Hyperopt minimizes 'loss', so lower RMSE = better
        return {
            "loss": eval_rmse,        # What hyperopt will optimize (minimize)
            "status": STATUS_OK,      # Successful run
            "model": model            # Save model for later retrieval
        }

In [ ]:
# ============================================================================
# STEP 6: Define Objective Function for Hyperopt
# ============================================================================
# Hyperopt needs an objective function that it can call repeatedly
# with different hyperparameters, and returns a loss value

def objective(params):
    """
    Wrapper function for hyperopt.
    Takes hyperparameters, trains a model, and returns the loss.
    
    Hyperopt will call this function many times with different parameters,
    always trying to find parameters that minimize the loss.
    """
    
    # Train model with these hyperparameters
    result = train_model(
        params,
        epochs=10,           # Number of training epochs (might be low for quick demo)
        train_x=train_x,
        train_y=train_y,
        valid_x=valid_x,
        valid_y=valid_y,
        test_x=test_x,
        test_y=test_y,
    )
    
    return result  # Return loss, status, and model

In [ ]:
# ============================================================================
# STEP 7: Define Hyperparameter Search Space
# ============================================================================
# Hyperopt needs to know:
# 1. Which hyperparameters to optimize
# 2. What range/distribution each can take

print("🎯 Defining hyperparameter search space...\n")

space = {
    # Learning Rate (lr): How quickly the model learns
    # - hp.loguniform: Search on logarithmic scale (good for learning rates)
    # - Range: 0.00001 to 0.1 (5 orders of magnitude)
    # - Logarithmic because 0.001 ≠ 0.1 is very different (not linear)
    "lr": hp.loguniform("lr", np.log(0.00001), np.log(0.1)),
    
    # Momentum: How much to keep previous gradient direction
    # - hp.uniform: Search on linear scale
    # - Range: 0.0 to 1.0 (0=no momentum, 1=pure momentum)
    "momentum": hp.uniform("momentum", 0.0, 1.0)
}

print("✅ Hyperparameter space defined:")
print("   - Learning Rate: 1e-5 to 1e-1 (log scale)")
print("   - Momentum: 0.0 to 1.0 (linear scale)")

In [ ]:
# ============================================================================
# STEP 8: Run Hyperopt Hyperparameter Search
# ============================================================================
# Hyperopt will:
# 1. Sample different hyperparameter combinations (up to max_evals)
# 2. Train a model for each combination (nested in MLflow)
# 3. Track the validation loss
# 4. Use Tree-structured Parzen Estimator (TPE) to suggest better params
# 5. Return the BEST hyperparameters found

print("🚀 Starting Hyperopt hyperparameter search...\n")
print("⚠️  This might take 2-3 minutes (training 4 models)\n")

# Connect to MLflow and create an experiment
mlflow.set_experiment("/wine-quality")  # All runs go under this experiment

# Start parent run (encompasses all hyperopt trials)
with mlflow.start_run():
    # ====================================================================
    # Run Hyperopt Search
    # ====================================================================
    # Create Trials object to store all trial information
    trials = Trials()  # Stores every hyperopt trial's results
    
    # Run the hyperparameter optimization
    best = fmin(
        fn=objective,                    # Function to minimize (trains model)
        space=space,                     # Hyperparameter search space
        algo=tpe.suggest,                # Algorithm: Tree Parzen Estimator (smart search)
        max_evals=4,                     # Try 4 different hyperparameter combinations
        trials=trials                    # Store results in trials object
    )
    
    print(f"\n✅ Hyperopt search complete!")
    print(f"   Tested 4 different hyperparameter combinations")
    
    # ====================================================================
    # Extract Best Results
    # ====================================================================
    # trials.results is a list of all trial results
    # Each result has 'loss' and 'model'
    # Sort by loss to get the best one
    best_run = sorted(trials.results, key=lambda x: x["loss"])[0]
    
    # ====================================================================
    # Log Best Results to MLflow
    # ====================================================================
    print(f"\n📊 Best hyperparameters found:")
    print(f"   Learning Rate: {best['lr']:.2e}")
    print(f"   Momentum: {best['momentum']:.4f}")
    print(f"   Validation RMSE: {best_run['loss']:.4f}")
    
    # Log best hyperparameters
    mlflow.log_params(best)
    
    # Log best metric
    mlflow.log_metric("best_validation_rmse", best_run["loss"])
    
    # Log best model (so we can use it for inference)
    mlflow.tensorflow.log_model(
        best_run["model"],
        "best_model",
        signature=signature
    )
    
    print(f"\n🎉 Best model saved and logged to MLflow!")
    print(f"📊 View all runs at: http://127.0.0.1:5000")

Epoch 1/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 49s 1s/step - loss: 36.0327 - root_mean_squared_error: 6.0027
13/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 35.1633 - root_mean_squared_error: 5.9296
24/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 34.5000 - root_mean_squared_error: 5.8732
35/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 33.9190 - root_mean_squared_error: 5.8232
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33.3819 - root_mean_squared_error: 5.7765
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 31.1920 - root_mean_squared_error: 5.5850 - val_loss: 27.2811 - val_root_mean_squared_error: 5.2231

Epoch 2/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 92ms/step - loss: 25.3485 - root_mean_squared_error: 5.0347
13/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.9075 - root_mean_squared_error: 5.0898
25/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.7350 - root_mean_squared_error: 5.0728
37/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.4446 - root_mean_squared_error: 5.0440
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.8799 - root_mean_squared_error: 4.8867 - val_loss: 20.9147 - val_root_mean_squared_error: 4.5733

Epoch 3/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 100ms/step - loss: 21.8093 - root_mean_squared_error: 4.6700
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.1067 - root_mean_squared_error: 4.4836
22/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.8673 - root_mean_squared_error: 4.4569
30/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.7048 - root_mean_squared_error: 4.4387
39/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 19.5214 - root_mean_squared_error: 4.4179
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 18.2889 - root_mean_squared_error: 4.2766 - val_loss: 16.0282 - val_root_mean_squared_error: 4.0035

Epoch 4/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 94ms/step - loss: 16.0692 - root_mean_squared_error: 4.0086
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.9451 - root_mean_squared_error: 3.9931
24/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.6416 - root_mean_squared_error: 3.9547
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 15.3195 - root_mean_squared_error: 3.9134
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.0097 - root_mean_squared_error: 3.7430 - val_loss: 12.3070 - val_root_mean_squared_error: 3.5081

Epoch 5/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - loss: 11.9208 - root_mean_squared_error: 3.4526
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.2164 - root_mean_squared_error: 3.4951
21/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12.0212 - root_mean_squared_error: 3.4670
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.8174 - root_mean_squared_error: 3.4373
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.5898 - root_mean_squared_error: 3.4036
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 10.7649 - root_mean_squared_error: 3.2810 - val_loss: 9.5077 - val_root_mean_squared_error: 3.0834

Epoch 6/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - loss: 9.1497 - root_mean_squared_error: 3.0249
 9/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.3315 - root_mean_squared_error: 3.0547
20/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.3024 - root_mean_squared_error: 3.0498
32/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.0973 - root_mean_squared_error: 3.0157
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9073 - root_mean_squared_error: 2.9838
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 8.3415 - root_mean_squared_error: 2.8882 - val_loss: 7.4504 - val_root_mean_squared_error: 2.7295

Epoch 7/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 85ms/step - loss: 8.4994 - root_mean_squared_error: 2.9154
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.6004 - root_mean_squared_error: 2.7563
23/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.3682 - root_mean_squared_error: 2.7137
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.2259 - root_mean_squared_error: 2.6873
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.0978 - root_mean_squared_error: 2.6632
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5726 - root_mean_squared_error: 2.5637 - val_loss: 5.9545 - val_root_mean_squared_error: 2.4402

Epoch 8/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 100ms/step - loss: 5.4276 - root_mean_squared_error: 2.3297
10/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.4384 - root_mean_squared_error: 2.3320
21/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.3683 - root_mean_squared_error: 2.3169
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.3404 - root_mean_squared_error: 2.3109
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.3515 - root_mean_squared_error: 2.3133
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 5.3100 - root_mean_squared_error: 2.3043 - val_loss: 4.9094 - val_root_mean_squared_error: 2.2157

Epoch 9/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 4.5861 - root_mean_squared_error: 2.1415
13/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.6849 - root_mean_squared_error: 2.1643
25/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.6868 - root_mean_squared_error: 2.1648
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.6513 - root_mean_squared_error: 2.1565
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.4255 - root_mean_squared_error: 2.1037 - val_loss: 4.1809 - val_root_mean_squared_error: 2.0447

Epoch 10/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 80ms/step - loss: 3.4231 - root_mean_squared_error: 1.8502
10/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.1294 - root_mean_squared_error: 2.0310
21/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.0860 - root_mean_squared_error: 2.0208
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9976 - root_mean_squared_error: 1.9988
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.9515 - root_mean_squared_error: 1.9873
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.8132 - root_mean_squared_error: 1.9527 - val_loss: 3.6790 - val_root_mean_squared_error: 1.9181

 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 3.6362 - root_mean_squared_error: 1.9069
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.6790 - root_mean_squared_error: 1.9181

  0%|          | 0/4 [00:07<?, ?trial/s, best loss=?]

2026/03/19 03:56:09 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\ryaka\AppData\Local\Temp\tmpr37m2lqi\model, flavor: tensorflow). Fall back to return ['tensorflow==2.20.0', 'cloudpickle==3.1.2']. Set logging level to DEBUG to see the full traceback.

Epoch 1/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 51s 1s/step - loss: 37.1485 - root_mean_squared_error: 6.0950
10/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 37.8847 - root_mean_squared_error: 6.1550
19/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 37.8739 - root_mean_squared_error: 6.1541
27/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 37.8796 - root_mean_squared_error: 6.1546
35/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 37.9296 - root_mean_squared_error: 6.1587
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 37.9568 - root_mean_squared_error: 6.1609
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 37.9049 - root_mean_squared_error: 6.1567 - val_loss: 37.5135 - val_root_mean_squared_error: 6.1248

Epoch 2/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 85ms/step - loss: 37.9967 - root_mean_squared_error: 6.1641
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 38.2623 - root_mean_squared_error: 6.1856
22/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37.9186 - root_mean_squared_error: 6.1577
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37.7271 - root_mean_squared_error: 6.1421
43/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37.6312 - root_mean_squared_error: 6.1343
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 37.3887 - root_mean_squared_error: 6.1146 - val_loss: 36.9996 - val_root_mean_squared_error: 6.0827

Epoch 3/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 95ms/step - loss: 38.9609 - root_mean_squared_error: 6.2419
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 38.0498 - root_mean_squared_error: 6.1679
22/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37.7268 - root_mean_squared_error: 6.1419
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37.5256 - root_mean_squared_error: 6.1255
42/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 37.4067 - root_mean_squared_error: 6.1159
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 36.8806 - root_mean_squared_error: 6.0729 - val_loss: 36.4937 - val_root_mean_squared_error: 6.0410

Epoch 4/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 36.2673 - root_mean_squared_error: 6.0222
13/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36.9380 - root_mean_squared_error: 6.0776
25/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 36.8654 - root_mean_squared_error: 6.0716
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36.7796 - root_mean_squared_error: 6.0646
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 36.3804 - root_mean_squared_error: 6.0316 - val_loss: 35.9957 - val_root_mean_squared_error: 5.9996

Epoch 5/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 99ms/step - loss: 34.4807 - root_mean_squared_error: 5.8720
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.8415 - root_mean_squared_error: 5.9866
21/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.9307 - root_mean_squared_error: 5.9941
31/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.8858 - root_mean_squared_error: 5.9904
42/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.8880 - root_mean_squared_error: 5.9906
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 35.8880 - root_mean_squared_error: 5.9907 - val_loss: 35.5053 - val_root_mean_squared_error: 5.9586

Epoch 6/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 90ms/step - loss: 35.4153 - root_mean_squared_error: 5.9511
 9/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 35.3684 - root_mean_squared_error: 5.9470
19/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 35.4861 - root_mean_squared_error: 5.9570
29/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 35.6033 - root_mean_squared_error: 5.9668
38/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 35.6322 - root_mean_squared_error: 5.9692
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 35.4031 - root_mean_squared_error: 5.9501 - val_loss: 35.0225 - val_root_mean_squared_error: 5.9180

Epoch 7/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 99ms/step - loss: 35.2582 - root_mean_squared_error: 5.9379
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.1960 - root_mean_squared_error: 5.9326
23/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.0138 - root_mean_squared_error: 5.9172
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34.9518 - root_mean_squared_error: 5.9120
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34.9360 - root_mean_squared_error: 5.9106
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 34.9256 - root_mean_squared_error: 5.9098 - val_loss: 34.5469 - val_root_mean_squared_error: 5.8777

Epoch 8/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - loss: 32.3894 - root_mean_squared_error: 5.6912
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34.2795 - root_mean_squared_error: 5.8546
23/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34.4206 - root_mean_squared_error: 5.8667
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34.4612 - root_mean_squared_error: 5.8703
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34.4697 - root_mean_squared_error: 5.8710
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34.4552 - root_mean_squared_error: 5.8699 - val_loss: 34.0784 - val_root_mean_squared_error: 5.8377

Epoch 9/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 35.3252 - root_mean_squared_error: 5.9435
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33.8747 - root_mean_squared_error: 5.8199
23/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33.9942 - root_mean_squared_error: 5.8303
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34.0934 - root_mean_squared_error: 5.8388
43/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34.0967 - root_mean_squared_error: 5.8391
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 33.9920 - root_mean_squared_error: 5.8303 - val_loss: 33.6170 - val_root_mean_squared_error: 5.7980

Epoch 10/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 87ms/step - loss: 33.7930 - root_mean_squared_error: 5.8132
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33.6105 - root_mean_squared_error: 5.7974
22/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 33.5544 - root_mean_squared_error: 5.7926
29/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 33.5083 - root_mean_squared_error: 5.7886
38/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 33.4973 - root_mean_squared_error: 5.7877
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 33.5354 - root_mean_squared_error: 5.7910 - val_loss: 33.1623 - val_root_mean_squared_error: 5.7587

 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 33.4088 - root_mean_squared_error: 5.7800
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 33.1623 - root_mean_squared_error: 5.7587

 25%|██▌       | 1/4 [00:24<00:51, 17.32s/trial, best loss: 1.9180818796157837]

2026/03/19 03:56:26 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\ryaka\AppData\Local\Temp\tmp0olswveg\model, flavor: tensorflow). Fall back to return ['tensorflow==2.20.0', 'cloudpickle==3.1.2']. Set logging level to DEBUG to see the full traceback.

Epoch 1/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 55s 1s/step - loss: 35.7322 - root_mean_squared_error: 5.9776
10/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 36.8122 - root_mean_squared_error: 6.0672
20/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 36.3890 - root_mean_squared_error: 6.0321
32/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 35.5865 - root_mean_squared_error: 5.9646
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 34.9843 - root_mean_squared_error: 5.9133
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 31.8645 - root_mean_squared_error: 5.6449 - val_loss: 26.2873 - val_root_mean_squared_error: 5.1271

Epoch 2/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 89ms/step - loss: 27.7505 - root_mean_squared_error: 5.2679
13/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.7372 - root_mean_squared_error: 5.0727
25/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25.0468 - root_mean_squared_error: 5.0039
37/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 24.4328 - root_mean_squared_error: 4.9415
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21.8431 - root_mean_squared_error: 4.6737 - val_loss: 17.8740 - val_root_mean_squared_error: 4.2278

Epoch 3/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - loss: 18.4138 - root_mean_squared_error: 4.2911
10/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 17.6079 - root_mean_squared_error: 4.1959
20/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 17.1564 - root_mean_squared_error: 4.1415
30/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16.7914 - root_mean_squared_error: 4.0969
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16.4159 - root_mean_squared_error: 4.0503
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 14.8004 - root_mean_squared_error: 3.8471 - val_loss: 12.0103 - val_root_mean_squared_error: 3.4656

Epoch 4/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - loss: 12.7111 - root_mean_squared_error: 3.5653
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.9331 - root_mean_squared_error: 3.4541
24/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.5020 - root_mean_squared_error: 3.3905
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 11.1233 - root_mean_squared_error: 3.3335
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.9527 - root_mean_squared_error: 3.1548 - val_loss: 8.1090 - val_root_mean_squared_error: 2.8476

Epoch 5/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 82ms/step - loss: 8.3690 - root_mean_squared_error: 2.8929
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.0466 - root_mean_squared_error: 2.8364
24/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.8192 - root_mean_squared_error: 2.7958
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7.5907 - root_mean_squared_error: 2.7541
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 6.7861 - root_mean_squared_error: 2.6050 - val_loss: 5.6468 - val_root_mean_squared_error: 2.3763

Epoch 6/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - loss: 5.7727 - root_mean_squared_error: 2.4026
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.4293 - root_mean_squared_error: 2.3299
22/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.3244 - root_mean_squared_error: 2.3073
33/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.2035 - root_mean_squared_error: 2.2806
44/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.1286 - root_mean_squared_error: 2.2641
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 4.8359 - root_mean_squared_error: 2.1991 - val_loss: 4.1830 - val_root_mean_squared_error: 2.0452

Epoch 7/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 105ms/step - loss: 4.9041 - root_mean_squared_error: 2.2145
13/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.1396 - root_mean_squared_error: 2.0339
25/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.0877 - root_mean_squared_error: 2.0213
37/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4.0076 - root_mean_squared_error: 2.0014
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.6894 - root_mean_squared_error: 1.9208 - val_loss: 3.3561 - val_root_mean_squared_error: 1.8320

Epoch 8/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 73ms/step - loss: 3.4764 - root_mean_squared_error: 1.8645
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.2881 - root_mean_squared_error: 1.8128
24/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.1511 - root_mean_squared_error: 1.7745
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.1157 - root_mean_squared_error: 1.7646
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.0340 - root_mean_squared_error: 1.7418 - val_loss: 2.8854 - val_root_mean_squared_error: 1.6987

Epoch 9/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 74ms/step - loss: 2.6151 - root_mean_squared_error: 1.6171
13/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7795 - root_mean_squared_error: 1.6670
25/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7721 - root_mean_squared_error: 1.6649
37/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.7527 - root_mean_squared_error: 1.6591
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.6494 - root_mean_squared_error: 1.6277 - val_loss: 2.6129 - val_root_mean_squared_error: 1.6165

Epoch 10/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 2.4062 - root_mean_squared_error: 1.5512
13/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5104 - root_mean_squared_error: 1.5839
25/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.5027 - root_mean_squared_error: 1.5817
37/46 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.4808 - root_mean_squared_error: 1.5748
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.4131 - root_mean_squared_error: 1.5534 - val_loss: 2.4405 - val_root_mean_squared_error: 1.5622

 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 2.4226 - root_mean_squared_error: 1.5565
11/12 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5021 - root_mean_squared_error: 1.5815
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 2.4405 - root_mean_squared_error: 1.5622

 50%|█████     | 2/4 [00:41<00:34, 17.39s/trial, best loss: 1.9180818796157837]

2026/03/19 03:56:44 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\ryaka\AppData\Local\Temp\tmpgbh29gqj\model, flavor: tensorflow). Fall back to return ['tensorflow==2.20.0', 'cloudpickle==3.1.2']. Set logging level to DEBUG to see the full traceback.

Epoch 1/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 52s 1s/step - loss: 40.6156 - root_mean_squared_error: 6.3730
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39.8249 - root_mean_squared_error: 6.3106
20/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 39.2649 - root_mean_squared_error: 6.2659
26/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 38.8744 - root_mean_squared_error: 6.2345
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 38.2112 - root_mean_squared_error: 6.1805
42/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 37.8489 - root_mean_squared_error: 6.1509
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 37.6139 - root_mean_squared_error: 6.1315
46/46 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 34.9901 - root_mean_squared_error: 5.9152 - val_loss: 29.5272 - val_root_mean_squared_error: 5.4339

Epoch 2/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 91ms/step - loss: 29.0440 - root_mean_squared_error: 5.3892
10/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 29.4138 - root_mean_squared_error: 5.4234
21/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.8485 - root_mean_squared_error: 5.3708
31/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 28.3252 - root_mean_squared_error: 5.3214
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 27.7841 - root_mean_squared_error: 5.2697
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 25.2819 - root_mean_squared_error: 5.0281 - val_loss: 21.3931 - val_root_mean_squared_error: 4.6253

Epoch 3/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 97ms/step - loss: 22.8212 - root_mean_squared_error: 4.7772
10/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.7444 - root_mean_squared_error: 4.6625
18/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.1003 - root_mean_squared_error: 4.5925
29/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 20.5016 - root_mean_squared_error: 4.5264
40/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 20.0517 - root_mean_squared_error: 4.4761
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 18.2817 - root_mean_squared_error: 4.2757 - val_loss: 15.4389 - val_root_mean_squared_error: 3.9292

Epoch 4/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 78ms/step - loss: 16.0476 - root_mean_squared_error: 4.0059
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.5038 - root_mean_squared_error: 3.9372
23/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 15.1516 - root_mean_squared_error: 3.8920
35/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.7401 - root_mean_squared_error: 3.8382
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14.4523 - root_mean_squared_error: 3.8001
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.1615 - root_mean_squared_error: 3.6279 - val_loss: 11.1000 - val_root_mean_squared_error: 3.3317

Epoch 5/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 11.1896 - root_mean_squared_error: 3.3451
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 11.0812 - root_mean_squared_error: 3.3288
21/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.7566 - root_mean_squared_error: 3.2792
31/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.4912 - root_mean_squared_error: 3.2381
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10.3016 - root_mean_squared_error: 3.2085
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 9.4867 - root_mean_squared_error: 3.0800 - val_loss: 8.0383 - val_root_mean_squared_error: 2.8352

Epoch 6/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 95ms/step - loss: 7.5860 - root_mean_squared_error: 2.7543
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.7868 - root_mean_squared_error: 2.7904
20/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6631 - root_mean_squared_error: 2.7680
28/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5869 - root_mean_squared_error: 2.7542
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.5123 - root_mean_squared_error: 2.7405
46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.4078 - root_mean_squared_error: 2.7212
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 6.9311 - root_mean_squared_error: 2.6327 - val_loss: 5.9455 - val_root_mean_squared_error: 2.4383

Epoch 7/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - loss: 4.7614 - root_mean_squared_error: 2.1821
 9/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.8181 - root_mean_squared_error: 2.4107
16/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.9254 - root_mean_squared_error: 2.4333
24/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.8895 - root_mean_squared_error: 2.4261
31/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.8039 - root_mean_squared_error: 2.4084
38/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5.7243 - root_mean_squared_error: 2.3917
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 5.2247 - root_mean_squared_error: 2.2858 - val_loss: 4.5857 - val_root_mean_squared_error: 2.1414

Epoch 8/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 88ms/step - loss: 4.4975 - root_mean_squared_error: 2.1207
11/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.6260 - root_mean_squared_error: 2.1506
22/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.6012 - root_mean_squared_error: 2.1449
32/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.5258 - root_mean_squared_error: 2.1271
41/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.4553 - root_mean_squared_error: 2.1103
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 4.1227 - root_mean_squared_error: 2.0304 - val_loss: 3.7206 - val_root_mean_squared_error: 1.9289

Epoch 9/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - loss: 2.8315 - root_mean_squared_error: 1.6827
12/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5336 - root_mean_squared_error: 1.8786
23/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5097 - root_mean_squared_error: 1.8727
34/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5244 - root_mean_squared_error: 1.8769
45/46 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3.5147 - root_mean_squared_error: 1.8744
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 3.4202 - root_mean_squared_error: 1.8494 - val_loss: 3.1701 - val_root_mean_squared_error: 1.7805

Epoch 10/10

 1/46 ━━━━━━━━━━━━━━━━━━━━ 4s 105ms/step - loss: 3.1377 - root_mean_squared_error: 1.7714
 9/46 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 3.0042 - root_mean_squared_error: 1.7328
18/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9352 - root_mean_squared_error: 1.7129
27/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9269 - root_mean_squared_error: 1.7105
36/46 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.9283 - root_mean_squared_error: 1.7110
46/46 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 2.9734 - root_mean_squared_error: 1.7243 - val_loss: 2.8234 - val_root_mean_squared_error: 1.6803

 1/12 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.4737 - root_mean_squared_error: 1.5728
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.8234 - root_mean_squared_error: 1.6803

 75%|███████▌  | 3/4 [00:59<00:17, 17.30s/trial, best loss: 1.5622018575668335]

2026/03/19 03:57:02 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\ryaka\AppData\Local\Temp\tmpvw3ly8vw\model, flavor: tensorflow). Fall back to return ['tensorflow==2.20.0', 'cloudpickle==3.1.2']. Set logging level to DEBUG to see the full traceback.

100%|██████████| 4/4 [01:10<00:00, 17.55s/trial, best loss: 1.5622018575668335]

2026/03/19 03:57:12 WARNING mlflow.utils.environment: Encountered an unexpected error while inferring pip requirements (model URI: C:\Users\ryaka\AppData\Local\Temp\tmpjv45vydp\model, flavor: tensorflow). Fall back to return ['tensorflow==2.20.0', 'cloudpickle==3.1.2']. Set logging level to DEBUG to see the full traceback.

Best Parameters: {'lr': np.float64(0.00010949955021246393), 'momentum': np.float64(0.7501479564130394)}
Best eval rmse: 1.5622018575668335

In [12]:
train[["quality"]].values

array([[6],
       [6],
       [5],
       ...,
       [6],
       [6],
       [8]], shape=(3673, 1))

In [ ]:
# ============================================================================
# STEP 9: Load and Use the Best Model (Inference)
# ============================================================================
# Now that we've found and trained the best model, let's use it for predictions!

print("🔮 Loading best model and making predictions...\n")

# Import MLflow serving utilities
from mlflow.models import validate_serving_input, convert_input_example_to_serving_input

# Model URI: unique identifier for the best model we just saved
# Format: runs:/[run_id]/best_model
# This tells MLflow which model to load
model_uri = 'runs:/faa29eb2b96243b19aae51014b5d1124/best_model'

# ====================================================================
# Generate Serving Payload
# ====================================================================
# MLflow needs to know what format the input data should be in
# for serving (like via REST API)
serving_payload = convert_input_example_to_serving_input(test_x)

print(f"✅ Serving payload generated")

# ====================================================================
# Validate Serving Input
# ====================================================================
# Make sure the model can actually serve predictions with this format
validate_serving_input(model_uri, serving_payload)

print(f"✅ Serving input validated")

d:\anaconda\envs\mlflow_env\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading artifacts: 100%|██████████| 7/7 [00:00<00:00, 298.77it/s]

39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

array([[6.1853533],
       [7.1047106],
       [6.47804  ],
       ...,
       [6.1623287],
       [6.804157 ],
       [5.9823923]], shape=(1225, 1), dtype=float32)

In [ ]:
# ============================================================================
# STEP 10: Make Predictions with the Best Model
# ============================================================================
# Load the model and make predictions on new data

print("🤖 Using the model for predictions...\n")

# Load model as a PyFuncModel (Python Function Model)
# PyFuncModel: Standard MLflow model format that can be deployed anywhere
model_uri = 'runs:/faa29eb2b96243b19aae51014b5d1124/best_model'
loaded_model = mlflow.pyfunc.load_model(model_uri)

print(f"✅ Model loaded successfully!")

# ====================================================================
# Make Predictions
# ====================================================================
# Use the loaded model to predict wine quality on test data
predictions = loaded_model.predict(pd.DataFrame(test_x))

print(f"✅ Predictions made on {len(test_x)} test samples!")
print(f"\n📊 Sample predictions (first 10):")
print(predictions[:10])

print(f"\n📊 Prediction statistics:")
print(f"   Mean predicted quality: {predictions.mean():.2f}")
print(f"   Std predicted quality: {predictions.std():.2f}")
print(f"   Min predicted quality: {predictions.min():.2f}")
print(f"   Max predicted quality: {predictions.max():.2f}")

39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

array([[6.1853533],
       [7.1047106],
       [6.47804  ],
       ...,
       [6.1623287],
       [6.804157 ],
       [5.9823923]], shape=(1225, 1), dtype=float32)

In [ ]:
# ============================================================================
# STEP 11: Register Model in MLflow Model Registry
# ============================================================================
# The Model Registry is like a "production catalog" for ML models
# 
# Benefits:
# - Track multiple versions of a model
# - Promote models from "staging" to "production"
# - Set up automatic deployment pipelines
# - A/B test different model versions
# - Roll back to previous versions if needed

print("📝 Registering best model in MLflow Model Registry...\n")

# Register the model with a descriptive name
# This allows other teams/services to find and use this model
mlflow.register_model(model_uri, "wine-quality")

print(f"✅ Model registered as 'wine-quality'!")
print(f"\n📊 Next steps:")
print(f"   1. Go to http://127.0.0.1:5000/models")
print(f"   2. Click on 'wine-quality' model")
print(f"   3. Promote versions through stages: Staging → Production")
print(f"   4. Use in other code with: mlflow.pyfunc.load_model('models:/wine-quality/production')")

Successfully registered model 'wine-quality'.
Created version '1' of model 'wine-quality'.

<ModelVersion: aliases=[], creation_timestamp=1773874576359, current_stage='None', description=None, last_updated_timestamp=1773874576359, name='wine-quality', run_id='faa29eb2b96243b19aae51014b5d1124', run_link=None, source='file:///d:/MLFlowStarter/2-DLFLOW/mlruns/510724209764455175/faa29eb2b96243b19aae51014b5d1124/artifacts/best_model', status='READY', status_message=None, tags={}, user_id=None, version=1>